### PR TITLE
remove: proc for param manipulation

### PR DESCRIPTION
**Pull request by repomaa**

### CODE REVIEW

**Review by vladfaust — CHANGES_REQUESTED** [review]
As seen at http://github.vladfaust.com/prism/Prism/Params.html, docs need updates too

**Comment by repomaa** [comment]
updated

**Review by vladfaust — CHANGES_REQUESTED** [review]
See http://github.vladfaust.com/prism/Prism/Params.html#type%28declaration%2C%2A%2Aoptions%29-macro

**Comment by repomaa** [comment]
yup, missed that, sorry. Updated.

**Pull request closed without merging**
